name: my_journey
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  shared_preferences: 2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Fonts/
    - assets/Online gallery-bro 1.png
    - assets/Bullet journal-bro 1.png
    - assets/Bibliophile-bro 1.png
    - assets/Frame 1 (2).png
    - assets/Frame 1 (3).png
    - assets/Frame 1 (4).png
    - assets/Personal settings-bro 1.png
    - assets/Profilepic.png
    - assets/Settings_off.png
    - assets/Settings_on.png
    - assets/Gallery_on.png
    - assets/Gallery_off.png
    - assets/Edit_on.png
    - assets/Edit_off.png
    - assets/home_off.png
    - assets/Home_on.png
    - assets/arrow.png
    - assets/Empty.png
    - assets/edit.png
    - assets/Back.png
  fonts:
    - family: CormorantUpright
      fonts:
        - asset: Fonts/CormorantUpright-Regular.ttf
        - asset: Fonts/CormorantUpright-Bold.ttf
          weight: 700
    - family: CourierPrime
      fonts:
        - asset: Fonts/CourierPrime-Regular.ttf
        - asset: Fonts/CourierPrime-Bold.ttf
          weight: 700
